# Config file for automatic testing at travis-ci.org
dist: xenial
language: python
cache: pip
sudo: false

python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
env:
  - DJANGO=1.8
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=3.2
matrix:
  exclude:
    - python: 3.5
      env: DJANGO=1.8
install:
  - pip install tox-travis coveralls

script:
  - tox

after_success: coveralls
